[package]
name = "fn_graph"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Batched function execution."
repository = "https://github.com/azriel91/fn_graph"
documentation = "https://docs.rs/fn_graph/"
readme = "README.md"
keywords = ["async", "batch", "dispatch", "function"]
license = "MIT OR Apache-2.0"

[dependencies]
fixedbitset = "0.4.0"
daggy = { version = "0.8.0", default-features = false }
futures = { version = "0.3.18", optional = true }
fn_meta = { version = "0.4.1", features = ["fn_meta_ext"] }
tokio = { version = "1.14.0", features = ["sync"] }

[dev-dependencies]
resman = { version = "0.11.0", features = ["debug", "fn_res", "fn_res_mut", "fn_meta"] }
tokio = { version = "1.14.0", features = ["rt", "sync", "time"] }

[features]
default = ["async"]
async = ["futures"]
