[package]
name = "fn_graph"
version = "0.2.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2021"
description = "Dynamically managed function graph execution."
repository = "https://github.com/azriel91/fn_graph"
documentation = "https://docs.rs/fn_graph/"
readme = "README.md"
keywords = ["async", "batch", "dispatch", "function", "graph"]
license = "MIT OR Apache-2.0"

[dependencies]
arrayvec = "0.7.2"
fixedbitset = "0.4.1"
daggy = { version = "0.8.0", default-features = false }
fn_meta = { version = "0.4.1", optional = true, features = ["fn_meta_ext"] }
futures = { version = "0.3.21", optional = true }
tokio = { version = "1.17.0", features = ["sync"] }

[dev-dependencies]
resman = { version = "0.11.0", features = ["debug", "fn_res", "fn_res_mut", "fn_meta"] }
tokio = { version = "1.17.0", features = ["rt", "sync", "time"] }

[features]
default = ["async"]
async = ["futures"]

[[example]]
name = "simple"
required-features = ["fn_meta"]
