[alias]
coverage_clean = ["llvm-cov", "clean", "--workspace"]
coverage_0 = ["llvm-cov", "--no-report", "nextest", "--features", ""]
coverage_1 = ["llvm-cov", "--no-report", "nextest", "--features", "fn_meta"]
coverage_2 = ["llvm-cov", "--no-report", "nextest", "--features", "resman"]
coverage_3 = ["llvm-cov", "--no-report", "nextest", "--all-features"]
coverage_merge = 'llvm-cov report --lcov --output-path ./target/coverage/lcov.info'
coverage_open = 'llvm-cov report --open --output-dir ./target/coverage'
